workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Configure Flutter
        script: |
          flutter config --no-enable-swift-package-manager
      - name: Get Dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          # Codemagic cleans and installs pods automatically if this fails
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - adloop.help@gmail.com