workflows:
  ios-workflow:
    name: iOS Workflow

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        provisioning_profiles:
          - AdLoopProductionNew

        certificates:
          - adloopdistribution

    integrations:
      app_store_connect: Codemagic

    scripts:
      - name: Flutter Clean
        script: |
          flutter clean

      - name: Get Flutter Packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration